<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Ecommerce.Service.Product.DataLayer</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.26" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.26" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.26">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <ProjectReference Include="..\Ecommerce.Service.Product.Domain.Product\Ecommerce.Service.Product.Domain.Product.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ecommerce.Common\Ecommerce.Common.csproj" />
  </ItemGroup>

</Project>
