<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Ecommerce.UI.ViewModel\Ecommerce.UI.ViewModel.csproj" />
    <ProjectReference Include="..\Ecommerce.UI.ServiceLayer\Ecommerce.UI.ServiceLayer.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
